name: 'demo_project'
config-version: 2
version: '1.0.0'

profile: 'demo_profile'
require-dbt-version: [">=1.0.0", "<2.0.0"]

model-paths: ["models"]
test-paths: ["tests"]

# seed-paths: ["seeds"]
# snapshot-paths: ["snapshots"]
# macro-paths: ["macros"]
# docs-paths: ["docs"]
# analysis-paths: ["analysis"]
# asset-paths: ["asset"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_modules"
  - "logs"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +persist_docs:
    relation: true
    columns: true

  # dbt_meta_testing
  # +required_docs: true
  
  # elementary
  # elementary:
  #   +schema: 'dq_elementary'

  demo_project:
    materialized: view
    staging:
      +schema: stage
      materialized: table
    marts:
      materialized: table


# snapshots:
#   +persist_docs:
#     relation: true
#     columns: true

# seeds:
#   +persist_docs:
#     relation: true
#     columns: true

# data_tests:
#   +store_failures: true
#   +schema: dq_tests